import os
os.environ["PYOPENGL_PLATFORM"] = "egl"
import argparse
import copy

import numpy as np
import torch
import imageio
from PIL import Image
from scipy.spatial.transform import Rotation as R

from pipeline.utils import (
    clean_name,
    load_image,
    collect_mask_paths,
    compute_fov_from_intrinsics,
    mesh_rendering,
    get_default_mesh_renderer,
)
# `inference` is exposed by submodule/Sam-3d-objects via PYTHONPATH; see the
# top-level shell scripts.
from inference import (
    Inference,
    make_scene,
    render_gs_view,
)


# Coordinate-system transform applied to SAM-3D-Objects mesh outputs to bring
# them into the world frame this pipeline operates in (rotates +Y -> +Z, etc.).
_SAM3D_TO_WORLD = np.array(
    [
        [1, 0, 0, 0],
        [0, 0, -1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ]
)

_DEFAULT_IMAGE_SIZE = (448, 448)


def _flip_xy(arr):
    """Negate the X and Y components in-place on an (N, 3+) array or tensor."""
    arr[:, 0] = -arr[:, 0]
    arr[:, 1] = -arr[:, 1]
    return arr


def _load_depth_with_fallback(image_dir, required_depth_path):
    """Prefer `depth_ori.npy` (raw AnySplat output) over `depth.npy`."""
    depth_ori_path = os.path.join(image_dir, "depth_ori.npy")
    if os.path.exists(depth_ori_path):
        return np.load(depth_ori_path)
    return np.load(required_depth_path)


def process_single_image(image_path, inference, args):
    """Run multi-object inference and asset export for one input image."""
    image_path = os.path.abspath(image_path)
    image_dir = os.path.dirname(image_path)

    # Optional scene scale factor produced by the AnySplat stage.
    scale_factor_path = os.path.join(image_dir, "scale.npy")
    if os.path.exists(scale_factor_path):
        scale_factor = float(np.asarray(np.load(scale_factor_path)).squeeze())
    else:
        scale_factor = 1.0
    print(f"Scale factor: {scale_factor}")

    pil_image = load_image(image_path)
    image_bg = np.array(pil_image)

    masks_dir = os.path.join(image_dir, "masks")
    mask_paths = collect_mask_paths(masks_dir)

    assets_dir = os.path.join(image_dir, "3d_assets")
    pt_dir = os.path.join(image_dir, "pt")

    if not mask_paths:
        print(f"Warning: No mask images found in {masks_dir}")
        print("Creating placeholder directories and continuing...")
        os.makedirs(assets_dir, exist_ok=True)
        os.makedirs(pt_dir, exist_ok=True)
        return

    os.makedirs(assets_dir, exist_ok=True)
    os.makedirs(pt_dir, exist_ok=True)

    required_files = {
        "extrinsic": os.path.join(image_dir, "extrinsic.npy"),
        "intrinsic": os.path.join(image_dir, "intrinsic.npy"),
        "depth": os.path.join(image_dir, "depth.npy"),
    }
    missing_files = [name for name, p in required_files.items() if not os.path.exists(p)]
    if missing_files:
        print(f"Warning: Missing required files: {missing_files}")
        print("These files should be generated by the AnySplat pipeline first.")
        return

    extrinsics = np.load(required_files["extrinsic"])
    intrinsics = np.load(required_files["intrinsic"])
    depth_anysplat = _load_depth_with_fallback(image_dir, required_files["depth"])

    fx_pixels = intrinsics[0, 0]
    fy_pixels = intrinsics[1, 1]

    image_size = _DEFAULT_IMAGE_SIZE
    _, fov_y = compute_fov_from_intrinsics(fx_pixels, fy_pixels, image_size, degrees=True)
    mesh_renderer = get_default_mesh_renderer(width=image_size[1], height=image_size[0])

    device = "cuda" if torch.cuda.is_available() else "cpu"

    for i, mask_path in enumerate(mask_paths):
        print(f"\n[{i+1}/{len(mask_paths)}] Processing mask: {mask_path}")

        # ===== Load and binarize mask =====
        mask_ = np.array(Image.open(mask_path).convert("L"))
        mask = np.where(mask_ > 0, 1, 0).astype("uint8")
        size_ori = np.sum(mask)

        depth_fg = depth_anysplat[mask > 0]
        if len(depth_fg) == 0:
            print("Warning: Mask has no valid depth values, skipping image.")
            return
        mean_depth_ori = depth_fg.mean()
        min_depth_ori = depth_fg.min()
        max_depth_ori = depth_fg.max()
        print(
            f"Depth in mask region: mean={mean_depth_ori:.4f}, "
            f"min={min_depth_ori:.4f}, max={max_depth_ori:.4f}"
        )

        mask_stem = clean_name(os.path.splitext(os.path.basename(mask_path))[0])
        save_path = os.path.join(pt_dir, f"{mask_stem}.pt")

        # ===== Run or load inference =====
        if os.path.exists(save_path):
            print(f"Loading cached inference result: {save_path}")
            out = torch.load(save_path, map_location=device, weights_only=False)
        else:
            print("Running inference on mask...")
            out = inference(image_bg, mask, seed=args.seed)
            if args.save_pt:
                torch.save(out, save_path)
                print(f"Saved inference result: {save_path}")

        gs_origin = copy.deepcopy(out["gs"])

        # ===== Optional intermediate GS preview before mesh alignment =====
        if args.save_intermediate:
            single_scene = make_scene(out)
            xyz_cv = _flip_xy(single_scene.get_xyz.clone())
            single_scene.from_xyz(xyz_cv)
            image_gs = render_gs_view(
                single_scene, extrinsics=extrinsics, fov_y=fov_y / 180 * np.pi
            )
            imageio.imwrite(
                os.path.join(image_dir, f"{mask_stem}_1_gs.png"), image_gs
            )
            single_scene.save_ply(
                os.path.join(assets_dir, f"{mask_stem}_gs_with_inferenced_pose.ply")
            )
        else:
            single_scene = None

        # ===== Pose parameters from SAM-3D-Objects =====
        rotation_output = out["rotation"].cpu().numpy()
        translation_output = out["translation"].cpu().numpy()
        scale_output = out["scale"].squeeze(0).cpu().numpy()

        print(f"Rotation (quaternion): {rotation_output}")
        print(f"Translation: {translation_output}")
        print(f"Scale: {scale_output}")

        if not out["glb"]:
            # No mesh produced for this object; skip to cleanup.
            if single_scene is not None:
                del single_scene
            del out
            torch.cuda.empty_cache()
            continue

        mesh = out["glb"]
        mesh.apply_transform(_SAM3D_TO_WORLD)
        mesh_origin = copy.deepcopy(mesh)

        # The pose transform below is only used to estimate object size from the
        # current view; the exported asset stays at the origin.
        quat = copy.deepcopy(rotation_output)
        rot = R.from_quat(quat, scalar_first=True).as_matrix().squeeze(0)
        inverse_rot = np.linalg.inv(rot)

        scale = np.broadcast_to(np.asarray(scale_output, dtype=float), (3,)).copy()
        scale_mat = np.diag(scale)

        transform = np.eye(4)
        transform[:3, :3] = inverse_rot @ scale_mat
        transform[:3, 3] = copy.deepcopy(translation_output)
        mesh.apply_transform(transform)
        _flip_xy(mesh.vertices)

        if args.save_intermediate:
            mesh.export(os.path.join(assets_dir, f"{mask_stem}_mesh_with_inferenced_pose.obj"))

        # ===== Render to recover scale by area + depth ratio =====
        mesh_copy = copy.deepcopy(mesh)
        color, depth = mesh_rendering(
            mesh=mesh_copy,
            extrinsics=extrinsics,
            fov_y=fov_y / 180 * np.pi,
            renderer=mesh_renderer,
        )
        if args.save_intermediate:
            imageio.imwrite(
                os.path.join(image_dir, f"{mask_stem}_1_mesh.png"), color
            )

        valid_depth = depth[depth > 0]
        if len(valid_depth) == 0:
            if single_scene is not None:
                del single_scene
            del out
            torch.cuda.empty_cache()
            continue

        mean_depth_sam3d = np.mean(valid_depth)
        size_new = np.sum(depth > 0)
        scale_factor_local = (
            np.sqrt(size_ori / size_new) * (mean_depth_ori / mean_depth_sam3d)
        )
        mesh.apply_scale(scale_factor_local)

        mesh_copy = mesh.copy()
        color, depth = mesh_rendering(
            mesh=mesh_copy,
            extrinsics=extrinsics,
            fov_y=fov_y / 180 * np.pi,
            renderer=mesh_renderer,
        )
        valid_depth = depth[depth > 0]
        mean_depth_sam3d_2 = np.mean(valid_depth)
        z_shift_2 = mean_depth_ori - mean_depth_sam3d_2
        mesh.vertices = mesh.vertices + np.array([0, 0, z_shift_2])

        if args.save_intermediate:
            transformed_mesh_path = os.path.join(assets_dir, f"{mask_stem}_mesh_final.obj")
            mesh.export(transformed_mesh_path)
            print(f"Saved transformed mesh: {transformed_mesh_path}")
            color, _ = mesh_rendering(
                mesh=mesh,
                extrinsics=extrinsics,
                fov_y=fov_y / 180 * np.pi,
                renderer=mesh_renderer,
            )
            imageio.imwrite(
                os.path.join(image_dir, f"{mask_stem}_mesh.png"), color
            )

        # ===== Final export at origin (mesh + GS) =====
        total_scale = float(scale_factor_local * scale_output[0]) / scale_factor
        print(
            f"Total scaling: {total_scale:.4f} "
            f"(local_scale={scale_factor_local:.4f}, "
            f"object_scale={scale_output[0]:.4f}, scene_scale={scale_factor})"
        )

        mesh_origin.apply_scale(total_scale)
        resized_mesh_path = os.path.join(assets_dir, f"{mask_stem}.obj")
        mesh_origin.export(resized_mesh_path)
        print(f"Saved resized mesh for mujoco: {resized_mesh_path}")

        final_mesh_mean_xyz = np.mean(mesh_origin.vertices, axis=0)
        mean_xyz_path = os.path.join(assets_dir, f"{mask_stem}_keyframe.npy")
        np.save(mean_xyz_path, final_mesh_mean_xyz)
        print(
            f"Final mesh mean XYZ: "
            f"[{final_mesh_mean_xyz[0]:.6f}, {final_mesh_mean_xyz[1]:.6f}, "
            f"{final_mesh_mean_xyz[2]:.6f}]"
        )
        print(f"Saved final mesh mean XYZ to: {mean_xyz_path}")

        if args.save_intermediate:
            # Apply the same transform to the GS scene so the debug snapshot
            # matches the mesh.
            xyz_cv = single_scene.get_xyz.clone() * scale_factor_local
            single_scene.from_xyz(xyz_cv)

            scale_t = single_scene.get_scaling * scale_factor_local
            single_scene.mininum_kernel_size *= scale_factor_local
            scale_t = torch.maximum(
                scale_t,
                torch.tensor(
                    gs_origin.mininum_kernel_size * 1.1,
                    device=scale_t.device,
                    dtype=scale_t.dtype,
                ),
            )
            single_scene.from_scaling(scale_t)

            xyz_cv = single_scene.get_xyz.clone()
            xyz_cv[:, 2] = xyz_cv[:, 2] + z_shift_2
            single_scene.from_xyz(xyz_cv)

            single_ply_path = os.path.join(assets_dir, f"{mask_stem}_gs_final.ply")
            single_scene.save_ply(single_ply_path)
            print(f"Saved transformed Gaussian: {single_ply_path}")
            image_gs = render_gs_view(
                single_scene, extrinsics=extrinsics, fov_y=fov_y / 180 * np.pi
            )
            imageio.imwrite(
                os.path.join(image_dir, f"{mask_stem}_gs.png"), image_gs
            )

        # Scale the original GS to mujoco units and save.
        xyz = gs_origin.get_xyz * total_scale
        gs_origin.from_xyz(xyz)

        scale_t = gs_origin.get_scaling * total_scale
        gs_origin.mininum_kernel_size *= total_scale
        scale_t = torch.maximum(
            scale_t,
            torch.tensor(
                gs_origin.mininum_kernel_size * 1.1,
                device=scale_t.device,
                dtype=scale_t.dtype,
            ),
        )
        gs_origin.from_scaling(scale_t)

        origin_ply_path = os.path.join(assets_dir, f"{mask_stem}.ply")
        gs_origin.save_ply(origin_ply_path)
        print(f"Saved resized Gaussian for mujoco: {origin_ply_path}")

        if single_scene is not None:
            del single_scene
        del out
        torch.cuda.empty_cache()

        print(f"Completed processing mask: {mask_stem}")

    print(f"\nAll masks processed for image: {image_path}")


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Run SAM-3D-Objects multi-object inference, save outputs to .pt, "
            "and reconstruct per-object Gaussian (.ply) and mesh (.obj) assets."
        )
    )
    parser.add_argument(
        "--project-root",
        type=str,
        default="submodule/Sam-3d-objects",
        help="Root directory of the sam-3d-objects project.",
    )
    parser.add_argument(
        "--input-dir",
        type=str,
        required=True,
        help="Input directory containing image folders.",
    )
    parser.add_argument(
        "--image-name",
        type=str,
        default="input_image.png",
        help="Name of the image file to process in each folder.",
    )
    parser.add_argument(
        "--tag",
        type=str,
        default="hf",
        help=(
            "Checkpoint tag, corresponds to "
            "submodule/Sam-3d-objects/checkpoints/{tag}/pipeline.yaml"
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed passed into Inference.__call__.",
    )
    parser.add_argument(
        "--save-pt",
        action="store_true",
        help="Save inference results to pt/*.pt. By default results are not saved.",
    )
    parser.add_argument(
        "--save-intermediate",
        action="store_true",
        help="Save intermediate debug outputs (e.g. *_1_gs.png, *_1_mesh.png).",
    )

    args = parser.parse_args()

    if os.path.isfile(args.input_dir):
        input_dir = os.path.dirname(os.path.abspath(args.input_dir))
    else:
        input_dir = os.path.abspath(args.input_dir)

    project_root = os.path.abspath(args.project_root)

    print(f"Project root (Sam-3d-objects): {project_root}")
    print(f"Input directory: {input_dir}")
    print(f"Looking for image files named: {args.image_name}")

    config_path = os.path.join(project_root, "checkpoints", args.tag, "pipeline.yaml")
    print(f"Loading model from config: {config_path}")
    inference = Inference(config_path, compile=False)
    print("Model loaded successfully")

    image_files = []
    for root, _dirs, files in os.walk(input_dir):
        for file in files:
            if file == args.image_name:
                image_files.append(os.path.join(root, file))

    print(f"Found {len(image_files)} image files to process")

    if not image_files:
        print(f"No {args.image_name} files found in {input_dir}")
        print("Directory structure:")
        for root, _dirs, files in os.walk(input_dir):
            level = root.replace(input_dir, "").count(os.sep)
            indent = " " * 2 * level
            print(f"{indent}{os.path.basename(root)}/")
            subindent = " " * 2 * (level + 1)
            for file in files:
                if file.lower().endswith((".png", ".jpg", ".jpeg")):
                    print(f"{subindent}{file}")
        return

    for idx, image_path in enumerate(image_files, 1):
        print(f"\n{'=' * 80}")
        print(f"Processing image {idx}/{len(image_files)}")
        print(f"Image path: {image_path}")
        print(f"{'=' * 80}")

        try:
            process_single_image(image_path, inference, args)
            print(f"Successfully processed: {image_path}")
        except Exception as e:
            print(f"Error processing {image_path}: {e}")
            import traceback
            traceback.print_exc()

    print(f"\n{'=' * 80}")
    print(f"All processing completed. Processed {len(image_files)} images.")
    print(f"{'=' * 80}")


if __name__ == "__main__":
    main()
