import os
os.environ["PYOPENGL_PLATFORM"] = "egl"
import glob
import argparse
import numpy as np
from scipy.spatial.transform import Rotation as R
import torch
from pipeline.utils import clean_name, load_image, load_binary_mask, collect_mask_paths, compute_fov_from_intrinsics, mesh_rendering, mesh_rendering_with_depth_adjustment
from inference import (
    Inference,
    make_scene,
    transform_mesh,
    ready_gaussian_for_video_rendering,
    render_video,
    render_gs_view,
    interactive_visualizer,
    _fix_gaussian_alignment
)
import copy
from PIL import Image
import cv2
import imageio


def process_single_image(image_path, inference, args):
    """处理单个图片的完整流程"""

    # 检查缩放因子文件
    scale_factor_path = os.path.join(image_path, 'scale.npy')
    scale_factor = np.load(scale_factor_path) if os.path.exists(scale_factor_path) else None
    print(f"Scale factor: {scale_factor}")
    # if scale_factor is not None:
    #     print(f"Scale factor: {scale_factor}")
    # else:
    #     print(f"Error: Scale factor file not found at {scale_factor_path}")
    #     print("Stopping function execution as scale_factor is required")
    #     return  # 或者 raise ValueError("Scale factor is required but not found")

    # 确保使用绝对路径
    image_path = os.path.abspath(image_path)
    image_dir = os.path.dirname(image_path)
    image_name = os.path.basename(image_path)
    
    print(f"Image directory: {image_dir}")
    print(f"Image name: {image_name}")
    
    # 读取图像
    pil_image = load_image(image_path)
    image_bg = np.array(pil_image)
    
    # 构建 mask 目录路径
    mask_dir = os.path.join(image_dir, 'masks')
    
    # 从 mask 目录收集 mask 路径
    mask_paths = collect_mask_paths(mask_dir)

    
    # 构建输出目录
    assets_dir = os.path.join(image_dir, '3d_assets')
    pt_dir = os.path.join(image_dir, 'pt')
    gif_dir = os.path.join(image_dir, 'gif')
    
    if not mask_paths:
        print(f"Warning: No mask images found in {mask_dir}")
        print("Creating placeholder files and continuing...")
        os.makedirs(assets_dir, exist_ok=True)
        os.makedirs(pt_dir, exist_ok=True)
        return
    
    os.makedirs(assets_dir, exist_ok=True)
    os.makedirs(pt_dir, exist_ok=True)
    os.makedirs(gif_dir, exist_ok=True)
    
    # 检查必要的文件是否存在
    required_files = {
        'extrinsic': os.path.join(image_dir, 'extrinsic.npy'),
        'intrinsic': os.path.join(image_dir, 'intrinsic.npy'),
        'depth': os.path.join(image_dir, 'depth.npy')
    }
    
    missing_files = []
    for name, path in required_files.items():
        if not os.path.exists(path):
            missing_files.append(name)
    
    if missing_files:
        print(f"Warning: Missing required files: {missing_files}")
        print(f"These files should be generated by the anysplat pipeline first")
        return
    
    # 加载相机参数和深度图
    extrinsics = np.load(required_files['extrinsic'])
    intrinsics = np.load(required_files['intrinsic'])
    depth_anysplat      = np.load(os.path.join(image_dir, 'depth_ori.npy')) if os.path.exists(os.path.join(image_dir, 'depth_ori.npy')) else np.load(required_files['depth'])
    
    
    
    # # 打印基本信息
    # print(f"\nCamera parameters for {os.path.basename(image_dir)}:")
    # print(f"Extrinsics shape: {extrinsics.shape}")
    # print(f"Intrinsics shape: {intrinsics.shape}")
    # print(f"Intrinsics matrix:\n{intrinsics}")
    
    fx_pixels = intrinsics[0, 0]
    fy_pixels = intrinsics[1, 1]
    cx_pixels = intrinsics[0, 2]
    cy_pixels = intrinsics[1, 2]
    # print(f"Pixel focal lengths: fx={fx_pixels:.2f}, fy={fy_pixels:.2f}")
    # print(f"Principal point: cx={cx_pixels:.2f}, cy={cy_pixels:.2f}")
    
    image_size = (448, 448)
    fov_x, fov_y = compute_fov_from_intrinsics(fx_pixels, fy_pixels, image_size, degrees=True)
    # print(f"Vertical FOV: {fov_y:.2f} degrees")
    # print(f"Horizontal FOV: {fov_x:.2f} degrees")
    
    # print(f"Depth map shape: {depth_anysplat.shape}")
    # print(f"Depth range: min={depth_anysplat.min():.4f}, max={depth_anysplat.max():.4f}, mean={depth_anysplat.mean():.4f}")
    

    all_gaussians = []
    bg_gaussian_path = os.path.join(assets_dir, 'bg_bridge.ply')
    
    mask_names = []
    masks = []
    original_sizes = []
    
    device = "cuda" if torch.cuda.is_available() else "cpu"
    
    # 处理每个mask
    for i, mask_path in enumerate(mask_paths):
        print(f"\n[{i+1}/{len(mask_paths)}] Processing mask: {mask_path}")
        
        # 加载掩码
        mask_ = np.array(Image.open(mask_path).convert("L"))
        mask = np.where(mask_ > 0, 1, 0).astype("uint8")
        
        mask_unique_values = np.unique(mask)
        print(f"Mask unique values: {mask_unique_values}")
        
        size_ori = np.sum(mask)
        original_sizes.append(size_ori)
        masks.append(mask)
        
        # 计算掩码区域的深度统计
        depth_fg = depth_anysplat[mask > 0]
        if len(depth_fg) > 0:
            mean_depth_ori = depth_fg.mean()
            min_depth_ori = depth_fg.min()
            max_depth_ori = depth_fg.max()
            print(f"Depth in mask region: mean={mean_depth_ori:.4f}, min={min_depth_ori:.4f}, max={max_depth_ori:.4f}")
        else:
            print("Warning: Mask has no valid depth values")
            mean_depth_ori = 0.0
            min_depth_ori = 0.0
            max_depth_ori = 0.0
        
        # 构造保存名字
        mask_stem_raw = os.path.splitext(os.path.basename(mask_path))[0]
        mask_stem = clean_name(mask_stem_raw)
        mask_names.append(mask_stem)
        
        # 保存二值化掩码
        cv2.imwrite(os.path.join(image_dir, f"{mask_stem}_binary.png"), mask * 255)
        
        # 保存路径
        save_name = f"{mask_stem}.pt"
        save_path = os.path.join(pt_dir, save_name)
        
        # 检查是否已存在处理结果
        if os.path.exists(save_path):
            print(f"Loading existing .pt file: {save_path}")
            out = torch.load(save_path, map_location=device, weights_only=False)
        else:
            print(f"Running inference on mask...")
            out = inference(image_bg, mask, seed=args.seed)
            torch.save(out, save_path)
            print(f"Saved inference result: {save_path}")
        
        # 复制高斯场景
        gs_origin = copy.deepcopy(out["gs"])
        
        # 创建场景并调整坐标系
        single_scene = make_scene(out)
        xyz = single_scene.get_xyz
        xyz_cv = xyz.clone()
        xyz_cv[:, 1] = -xyz[:, 1]  # Y轴翻转
        xyz_cv[:, 0] = -xyz[:, 0]  # X轴翻转
        single_scene.from_xyz(xyz_cv)
        # 第一次变换的高斯
        image_gs = render_gs_view(single_scene, extrinsics=extrinsics, fov_y=fov_y/180*np.pi)
        gs_image_path = os.path.join(image_dir, f"{mask_stem}_1_gs.png")
        imageio.imwrite(gs_image_path, image_gs)
        single_ply_path = os.path.join(assets_dir, f"{mask_stem}_gs_with_inferenced_pose.ply")
        single_scene.save_ply(single_ply_path)  # 根据需要取消注释
        
        # 保存未变换的高斯
        untransformed_ply_path = os.path.join(assets_dir, f"{mask_stem}_gs_untransformed.ply")
        # out["gs"].save_ply(untransformed_ply_path)  # 根据需要取消注释
        # print(f"Saved untransformed Gaussian: {untransformed_ply_path}")
        
        # 提取位姿参数
        rotation_output = out['rotation'].cpu().numpy()
        translation_output = out['translation'].cpu().numpy()
        scale_output = out['scale'].squeeze(0).cpu().numpy()
        
        print(f"Rotation (quaternion): {rotation_output}")
        print(f"Translation: {translation_output}")
        print(f"Scale: {scale_output}")
        
        # 处理网格（如果存在）
        if out['glb']:
            mesh = out['glb']
            
            # # 保存未变换的网格
            # untransformed_mesh_path = os.path.join(assets_dir, f"{mask_stem}_mesh_untransformed.obj")
            # mesh.export(untransformed_mesh_path)  # 根据需要取消注释
            # print(f"Saved untransformed mesh: {untransformed_mesh_path}")
            
            # 坐标系对齐变换
            rot_coordinate_transform = np.array([
                [1, 0, 0, 0],
                [0, 0, -1, 0],
                [0, 1, 0, 0],
                [0, 0, 0, 1]
            ])
            
            first_transformed_mesh_path = os.path.join(assets_dir, f"{mask_stem}_mesh_coordinates_aligned.obj")
            mesh.apply_transform(rot_coordinate_transform)
            mesh_origin = copy.deepcopy(mesh)
            # mesh.export(first_transformed_mesh_path)  # 根据需要取消注释
            print(f"Saved coordinate-aligned mesh: {first_transformed_mesh_path}")
            
            # 应用变换矩阵
            quat = copy.deepcopy(rotation_output)
            rot = R.from_quat(quat, scalar_first=True).as_matrix().squeeze(0)
            inverse_rot = np.linalg.inv(rot)
            
            # 处理缩放
            if np.isscalar(scale_output):
                scale = np.array([scale_output, scale_output, scale_output])
            else:
                scale = np.asarray(scale_output)
            
            scale_mat = np.diag(scale)
            
            # 构建变换矩阵
            transform = np.eye(4)
            transform[:3, :3] = inverse_rot @ scale_mat
            transform[:3, 3] = copy.deepcopy(translation_output)
            
            # 应用变换
            mesh.apply_transform(transform)
            mesh.vertices[:, 1] = -mesh.vertices[:, 1]  # Y轴取反
            mesh.vertices[:, 0] = -mesh.vertices[:, 0]  # X轴取反
            mesh.export(os.path.join(assets_dir, f"{mask_stem}_mesh_with_inferenced_pose.obj"))  # 根据需要取消注释
            
            # 渲染并调整深度
            mesh_copy = copy.deepcopy(mesh)
            color, depth = mesh_rendering(mesh=mesh_copy, extrinsics=extrinsics, fov_y=fov_y/180*np.pi)
            # 第一次变换的mesh
            mesh_image_path = os.path.join(image_dir, f"{mask_stem}_1_mesh.png")
            imageio.imwrite(mesh_image_path, color)
            
            valid_depth = depth[depth > 0]
            if len(valid_depth) > 0:
                mean_depth_sam3d = np.mean(valid_depth)
                size_new = np.sum(depth > 0)
                scale_factor_local = np.sqrt(size_ori / size_new) * (mean_depth_ori / mean_depth_sam3d) 
                mesh.apply_scale(scale_factor_local)
                mesh_copy = mesh.copy()
                color, depth = mesh_rendering(mesh=mesh_copy, extrinsics=extrinsics, fov_y=fov_y/180*np.pi)
                valid_depth = depth[depth > 0]
                mean_depth_sam3d_2 = np.mean(valid_depth)
                z_shift_2 = mean_depth_ori - mean_depth_sam3d_2
                mesh.vertices = mesh.vertices + np.array([0, 0, z_shift_2])
                 # 保存最终变换的网格
                transformed_mesh_path = os.path.join(assets_dir, f"{mask_stem}_mesh_final.obj")
                mesh.export(transformed_mesh_path)  # 根据需要取消注释
                print(f"Saved transformed mesh: {transformed_mesh_path}")
                # 渲染输入图片视角下的mesh
                color, depth = mesh_rendering(mesh=mesh, extrinsics=extrinsics, fov_y=fov_y/180*np.pi)
                mesh_image_path = os.path.join(image_dir, f"{mask_stem}_mesh.png")
                imageio.imwrite(mesh_image_path, color)              
               

                # === 新增：保存最后调整后的mesh平均坐标 ===
                # 计算经过所有变换后的mesh顶点平均坐标
                if scale_factor is not None:
                    final_mesh_vertices = mesh.vertices / scale_factor
                    final_mesh_mean_xyz = np.mean(final_mesh_vertices, axis=0)
                else:
                    final_mesh_vertices = mesh.vertices            
                    final_mesh_mean_xyz = np.mean(final_mesh_vertices, axis=0)
                # 保存到npy文件
                mean_xyz_path = os.path.join(assets_dir, f"{mask_stem}_keyframe.npy")
                np.save(mean_xyz_path, final_mesh_mean_xyz)
                
                print(f"Final mesh mean XYZ: [{final_mesh_mean_xyz[0]:.6f}, {final_mesh_mean_xyz[1]:.6f}, {final_mesh_mean_xyz[2]:.6f}]")
                print(f"Saved final mesh mean XYZ to: {mean_xyz_path}")
                
                # 计算总缩放因子
                if scale_factor is not None:
                    total_scale = float(scale_factor_local * scale_output[0]) / scale_factor
                else:
                    total_scale = float(scale_factor_local * scale_output[0])
                
                print(f"Total scaling: {total_scale:.4f} (local_scale={scale_factor_local:.4f}, object_scale={scale_output[0]:.4f}, scene_scale={scale_factor if scale_factor is not None else 1.0})")
                
                # 缩放原始网格并保存
                mesh_origin.apply_scale(total_scale)
                resized_mesh_path = os.path.join(assets_dir, f"{mask_stem}.obj")
                mesh_origin.export(resized_mesh_path)
                print(f"Saved resized mesh for mujoco: {resized_mesh_path}")
                
                # 对高斯进行相同的变换   目前不需要保存最后的高斯
                xyz = single_scene.get_xyz
                xyz_cv = xyz.clone()
                xyz_cv = xyz_cv * scale_factor_local  # 缩放
                single_scene.from_xyz(xyz_cv)
                
                scale = single_scene.get_scaling * scale_factor_local
                single_scene.mininum_kernel_size *= scale_factor_local
                scale = torch.maximum(
                        scale,
                        torch.tensor(
                            gs_origin.mininum_kernel_size * 1.1,
                            device = scale.device,
                            dtype=scale.dtype,
                        )
                    )
                single_scene.from_scaling(scale)
                
                xyz = single_scene.get_xyz
                xyz_cv = xyz.clone()
                xyz_cv[:, 2] = xyz[:, 2] + z_shift_2  # 第二次深度调整
                single_scene.from_xyz(xyz_cv)
                
                # 保存最终变换的高斯
                single_ply_path = os.path.join(assets_dir, f"{mask_stem}_gs_final.ply")
                single_scene.save_ply(single_ply_path)  # 根据需要取消注释
                print(f"Saved transformed Gaussian: {single_ply_path}")
                # 渲染输入图片视角下的3dgs
                image_gs = render_gs_view(single_scene, extrinsics=extrinsics, fov_y=fov_y/180*np.pi)
                gs_image_path = os.path.join(image_dir, f"{mask_stem}_gs.png")
                imageio.imwrite(gs_image_path, image_gs)

                all_gaussians.append(single_scene)

                # # 渲染视频
                # video = render_video(
                #     out["gs"],
                #     r=1.4,
                #     fov=60,
                #     resolution=512,
                # )["color"]

                # single_gif_path = os.path.join(gif_dir, f"{mask_stem}.gif")
                # imageio.mimsave(
                #     single_gif_path,
                #     video,
                #     format="GIF",
                #     duration=1000 / 30,  # 30fps
                #     loop=0,
                # )
                # print(f"🎞️ Saved single-object GIF: {single_gif_path}")
    
                # 缩放原始高斯并保存
                xyz = gs_origin.get_xyz
                
                xyz = xyz * total_scale
                gs_origin.from_xyz(xyz)
                
                scale = gs_origin.get_scaling * total_scale 
                gs_origin.mininum_kernel_size *= total_scale 
                scale = torch.maximum(
                        scale,
                        torch.tensor(
                            gs_origin.mininum_kernel_size * 1.1,
                            device = scale.device,
                            dtype=scale.dtype,
                        )
                    )
                gs_origin.from_scaling(scale)
                
                origin_ply_path = os.path.join(assets_dir, f"{mask_stem}.ply")
                gs_origin.save_ply(origin_ply_path)
                print(f"Saved resized Gaussian for mujoco: {origin_ply_path}")
        
        # 清理显存
        del single_scene
        del out
        torch.cuda.empty_cache()
        
        print(f"✓ Completed processing mask: {mask_stem}")

    gaussian_bg = copy.deepcopy(all_gaussians[0])
    gaussian_bg.load_ply(bg_gaussian_path)
    all_gaussians.append(gaussian_bg)

    # 2. 合并所有高斯
    scene_gs = all_gaussians[0]
    # 初始化 scene_gs
    if not hasattr(scene_gs, "_opacity") or scene_gs._opacity is None:
        scene_gs._opacity = torch.ones(scene_gs._xyz.shape[0], device=scene_gs._xyz.device)
    
    for gs in all_gaussians[1:]:
        if not hasattr(gs, "_opacity") or gs._opacity is None:
            gs._opacity = torch.ones(gs._xyz.shape[0], device=gs._xyz.device)
        
        # 扩展 _scaling 和 _rotation 以匹配 _xyz
        if gs._scaling.ndim == 1:
            gs._scaling = gs._scaling.unsqueeze(0).expand(gs._xyz.shape[0], -1)
        if gs._rotation.ndim == 1:
            gs._rotation = gs._rotation.unsqueeze(0).expand(gs._xyz.shape[0], -1)

        scene_gs._xyz = torch.cat([scene_gs._xyz, gs._xyz], dim=0)
        scene_gs._features_dc = torch.cat([scene_gs._features_dc, gs._features_dc], dim=0)
        scene_gs._scaling = torch.cat([scene_gs._scaling, gs._scaling], dim=0)
        scene_gs._rotation = torch.cat([scene_gs._rotation, gs._rotation], dim=0)
        scene_gs._opacity = torch.cat([scene_gs._opacity, gs._opacity], dim=0)

        scene_gs.mininum_kernel_size = min(scene_gs.mininum_kernel_size, gs.mininum_kernel_size)
    
    # 3. 渲染
    rendered_image = render_gs_view(scene_gs, extrinsics=extrinsics, fov_y=fov_y/180*np.pi)
    all_gs_image_path = os.path.join(image_dir, f"bridge_gs.png")
    imageio.imwrite(all_gs_image_path, rendered_image)
    
    print(f"\n✅ All masks processed for image: {image_path}")

def main():
    parser = argparse.ArgumentParser(
        description="Run SAM3D multi-object inference and save outputs to .pt, and reconstruct single object Gaussian .ply"
    )
    parser.add_argument(
        "--project-root",
        type=str,
        default="Sam-3d-objects",
        help="Root directory of sam-3d-objects project.",
    )
    parser.add_argument(
        "--save-dir",
        type=str,
        default="sam-3d-objects/torch_save_pt",
        help="Directory containing *.pt files.",
    )
    parser.add_argument(
        "--input-dir",
        type=str,
        required=True,
        help="Input directory containing image folders.",
    )
    parser.add_argument(
        "--image-name",
        type=str,
        default="input_image.png",
        help="Name of the image file to process in each folder.",
    )
    parser.add_argument(
        "--tag",
        type=str,
        default="hf",
        help="Checkpoint tag, corresponds to ../Sam-3d-objects/checkpoints/{tag}/pipeline.yaml",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed passed into Inference.__call__.",
    )
    
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    if os.path.isfile(args.input_dir):
        input_dir = os.path.dirname(os.path.abspath(args.input_dir))
    else:
        input_dir = os.path.abspath(args.input_dir)

    
    if args.project_root is not None:
        project_root = os.path.abspath(args.project_root)
    else:
        project_root = os.path.abspath(os.path.join(script_dir, "..", "Sam-3d-objects"))

    print(f"Project root (Sam-3d-objects): {project_root}")
    print(f"Input directory: {input_dir}")
    print(f"Looking for image files named: {args.image_name}")

    # 加载模型（只加载一次）
    config_path = os.path.join(project_root, "checkpoints", args.tag, "pipeline.yaml")
    print(f"Loading model from config: {config_path}")
    inference = Inference(config_path, compile=False)
    print("Model loaded successfully")

#     # 定义需要包含的轨迹关键字
#     # 使用列表推导式生成 traj0_0 到 traj0_15
#    # 1. 使用 range(16) 生成 0-15 的列表
#     valid_trajs = {f"traj0_{i}" for i in range(15)}
    
#     image_files = []
#     for root, dirs, files in os.walk(input_dir):
#         # 2. 将路径按分隔符切开，得到文件夹名称列表
#         # 例如: /home/data/traj0_16 -> ['home', 'data', 'traj0_16']
#         path_parts = os.path.normpath(root).split(os.sep)
        
#         # 3. 使用集合交集判断：检查路径中是否有任何一个文件夹名【完全等于】关键字
#         if any(part in valid_trajs for part in path_parts):
#             for file in files:
#                 if file == args.image_name:
#                     image_path = os.path.join(root, file)
#                     print(image_path)
#                     image_files.append(image_path)
    
#     print(f"Found {len(image_files)} image files matching traj0_0-15 criteria")
    
    # 查找所有input_image.png文件
    image_files = []
    for root, dirs, files in os.walk(input_dir):
        for file in files:
            if file == args.image_name:
                image_path = os.path.join(root, file)
                image_files.append(image_path)
    
    print(f"Found {len(image_files)} image files to process")
    
    if len(image_files) == 0:
        print(f"No {args.image_name} files found in {input_dir}")
        print("Directory structure:")
        for root, dirs, files in os.walk(input_dir):
            level = root.replace(input_dir, '').count(os.sep)
            indent = ' ' * 2 * level
            print(f'{indent}{os.path.basename(root)}/')
            subindent = ' ' * 2 * (level + 1)
            for file in files:
                if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                    print(f'{subindent}{file}')
        return
    
    # 处理每个图像文件
    for idx, image_path in enumerate(image_files, 1):
        print(f"\n{'='*80}")
        print(f"Processing image {idx}/{len(image_files)}")
        print(f"Image path: {image_path}")
        print(f"{'='*80}")
        
        try:
            process_single_image(image_path, inference, args)
            print(f"✓ Successfully processed: {image_path}")
        except Exception as e:
            print(f"✗ Error processing {image_path}: {str(e)}")
            import traceback
            traceback.print_exc()
    
    print(f"\n{'='*80}")
    print(f"All processing completed! Processed {len(image_files)} images")
    print(f"{'='*80}")


if __name__ == "__main__":
    main()
